Repository Coders-Dorm/Best-Of-Chrome-Extensions, pull requests merged in 2022-10, with the labels that each got.

#16 Created a to-do list chrome extension
  To-do list chrome extension/index.css
  To-do list chrome extension/index.html
  To-do list chrome extension/logo.png
  To-do list chrome extension/manifest.json
  To-do list chrome extension/script.js
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#22 Calculator Extension
  Calculator extension/Readme.md
  Calculator extension/index.html
  Calculator extension/logo.png
  Calculator extension/manifest.json
  Calculator extension/script.js
  Calculator extension/style.css
Labels: hacktoberfest-accepted

#34 Note maker extension
  note maker/i.md
  note maker/package.json
  note maker/src/assets/banner.png
  note maker/src/assets/github-logo.png
  note maker/src/assets/icon128.png
  note maker/src/assets/icon16.png
  note maker/src/assets/icon48.png
  note maker/src/background.ts
  note maker/src/content-scripts/main.css
  note maker/src/content-scripts/main.ts
  note maker/src/content-scripts/parser/selection-meta.ts
  note maker/src/content-scripts/parser/text-list.ts
  note maker/src/content-scripts/renderer/dom/logo-icon.ts
  note maker/src/content-scripts/renderer/dom/rect.ts
  note maker/src/content-scripts/renderer/popup/footer/ex-import.ts
  note maker/src/content-scripts/renderer/popup/footer/index.vue
  note maker/src/content-scripts/renderer/popup/index.vue
  note maker/src/content-scripts/renderer/popup/note-book/index.vue
  note maker/src/content-scripts/renderer/popup/note-book/note-list.vue
  note maker/src/content-scripts/renderer/popup/note-book/note.vue
  note maker/src/content-scripts/renderer/popup/shared/more.vue
  note maker/src/content-scripts/renderer/popup/tag-book/index.vue
  note maker/src/content-scripts/renderer/popup/tag-book/tag-searcher.vue
  note maker/src/content-scripts/renderer/popup/tag-book/tag-selector/index.vue
  note maker/src/content-scripts/renderer/popup/tag-book/tag-selector/tag-list.vue
  note maker/src/global.d.ts
  note maker/src/manifest.json
  note maker/src/shims-vue.d.ts
  note maker/src/types/common.ts
  note maker/src/types/dom.ts
  note maker/src/types/note.ts
  note maker/src/types/storage.ts
  note maker/src/types/tag.ts
  note maker/src/utils/constant.ts
  note maker/src/utils/dom.ts
  note maker/src/utils/mitt.ts
  note maker/src/utils/storage.ts
  note maker/src/utils/text.ts
  note maker/src/utils/utils.ts
  note maker/tsconfig.json
  note maker/vite.config.ts
  note maker/yarn.lock
Labels: good first issue, hacktoberfest-accepted

#35 Added Youtube ad blocker Extension
  Youtube AD Blocker/README.md
  Youtube AD Blocker/ext.js
  Youtube AD Blocker/icon.png
  Youtube AD Blocker/manifest.json
Labels: good first issue, hacktoberfest

#41 Added Internet Speed Test Extension
  Internet Speed Test/Content/Fonts/Ubuntu/Ubuntu-Bold.ttf
  Internet Speed Test/Content/Fonts/Ubuntu/Ubuntu-Medium.ttf
  Internet Speed Test/Content/Fonts/Ubuntu/Ubuntu-Regular.ttf
  Internet Speed Test/Content/Fonts/Ubuntu/Ubuntu.css
  Internet Speed Test/Content/Fonts/config.json
  Internet Speed Test/Content/Fonts/css/animation.css
  Internet Speed Test/Content/Fonts/css/fontello-codes.css
  Internet Speed Test/Content/Fonts/css/fontello-embedded.css
  Internet Speed Test/Content/Fonts/css/fontello-ie7-codes.css
  Internet Speed Test/Content/Fonts/css/fontello-ie7.css
  Internet Speed Test/Content/Fonts/css/fontello.css
  Internet Speed Test/Content/Fonts/font/fontello.eot
  Internet Speed Test/Content/Fonts/font/fontello.svg
  Internet Speed Test/Content/Fonts/font/fontello.ttf
  Internet Speed Test/Content/Fonts/font/fontello.woff
  Internet Speed Test/Content/Fonts/font/fontello.woff2
  Internet Speed Test/Content/Global.css
  Internet Speed Test/Content/Images/128.png
  Internet Speed Test/Content/Images/16.png
  Internet Speed Test/Content/Images/24.png
  Internet Speed Test/Content/Images/256.png
  Internet Speed Test/Content/Images/32.png
  Internet Speed Test/Content/Images/48.png
  Internet Speed Test/Content/Images/64.png
  Internet Speed Test/Content/Images/Background2.jpg
  Internet Speed Test/Content/Options.css
  Internet Speed Test/Content/Reset.css
  Internet Speed Test/Content/Style.css
  Internet Speed Test/Default.html
  Internet Speed Test/Resources/speedtest-servers.xml
  Internet Speed Test/Script/AsyncRequest.js
  Internet Speed Test/Script/GetServers.js
  Internet Speed Test/Script/Main.js
  Internet Speed Test/Script/background.js
  Internet Speed Test/Script/gauge.js
  Internet Speed Test/manifest.json
Labels: good first issue, hacktoberfest-accepted, feature

#46 Added Zoom-Gmeet Attendance Extension
  Zoom-Gmeet Attendance/logo/128.png
  Zoom-Gmeet Attendance/logo/16.png
  Zoom-Gmeet Attendance/logo/48.png
  Zoom-Gmeet Attendance/main.js
  Zoom-Gmeet Attendance/manifest.json
Labels: good first issue, hacktoberfest-accepted, feature

#56 Added Dictionary Extension
  Dictionary Extension/loading.svg
  Dictionary Extension/logo.png
  Dictionary Extension/manifest.json
  Dictionary Extension/popup.html
  Dictionary Extension/script.js
  Dictionary Extension/styles.css
Labels: hacktoberfest-accepted

#61 THE_TALKER
  The-TALKER2.0/README.md
  The-TALKER2.0/_locales/en/messages.json
  The-TALKER2.0/_locales/es/messages.json
  The-TALKER2.0/_locales/it/messages.json
  The-TALKER2.0/_locales/ja/messages.json
  The-TALKER2.0/_locales/vi/messages.json
  The-TALKER2.0/_locales/zh_CN/messages.json
  The-TALKER2.0/_locales/zh_TW/messages.json
  The-TALKER2.0/css/MaterialIcons-Regular.woff
  The-TALKER2.0/css/bootstrap.min.css
  The-TALKER2.0/css/common.css
  The-TALKER2.0/css/images/ui-bg_diagonals-small_40_db4865_40x40.png
  The-TALKER2.0/css/images/ui-bg_diagonals-small_50_93c3cd_40x40.png
  The-TALKER2.0/css/images/ui-bg_diagonals-small_50_ff3853_40x40.png
  The-TALKER2.0/css/images/ui-bg_diagonals-small_75_ccd232_40x40.png
  The-TALKER2.0/css/images/ui-bg_dots-medium_80_ffff38_4x4.png
  The-TALKER2.0/css/images/ui-bg_dots-small_35_35414f_2x2.png
  The-TALKER2.0/css/images/ui-bg_white-lines_85_f7f7ba_40x100.png
  The-TALKER2.0/css/images/ui-icons_454545_256x240.png
  The-TALKER2.0/css/images/ui-icons_88a206_256x240.png
  The-TALKER2.0/css/images/ui-icons_c02669_256x240.png
  The-TALKER2.0/css/images/ui-icons_e1e463_256x240.png
  The-TALKER2.0/css/images/ui-icons_ffeb33_256x240.png
  The-TALKER2.0/css/images/ui-icons_ffffff_256x240.png
  The-TALKER2.0/css/options.css
  The-TALKER2.0/css/popup.css
  The-TALKER2.0/img/icon-48.png
  The-TALKER2.0/img/loading.gif
  The-TALKER2.0/img/talker_icon.png
  The-TALKER2.0/js/aws-sdk.js
  The-TALKER2.0/js/content.js
  The-TALKER2.0/js/content/google-doc.js
  The-TALKER2.0/js/content/google-drive-doc.js
  The-TALKER2.0/js/content/google-drive-preview.js
  The-TALKER2.0/js/content/google-play-book.js
  The-TALKER2.0/js/content/google-slides.js
  The-TALKER2.0/js/content/googleDocsUtil.js
  The-TALKER2.0/js/content/html-doc.js
  The-TALKER2.0/js/content/ixl.js
  The-TALKER2.0/js/content/pdf-doc.js
  The-TALKER2.0/js/custom-voices.js
  The-TALKER2.0/js/defaults.js
  The-TALKER2.0/js/document.js
  The-TALKER2.0/js/events.js
  The-TALKER2.0/js/google-translate.js
  The-TALKER2.0/js/jquery-3.1.1.min.js
  The-TALKER2.0/js/languages.js
  The-TALKER2.0/js/options.js
  The-TALKER2.0/js/popup.js
  The-TALKER2.0/js/speech.js
  The-TALKER2.0/js/tts-engines.js
  The-TALKER2.0/manifest.json
  The-TALKER2.0/options.html
  The-TALKER2.0/package-lock.json
  The-TALKER2.0/package.json
  The-TALKER2.0/popup.html
  The-TALKER2.0/sound/silence.mp3
Labels: good first issue, hacktoberfest-accepted, feature

#65 Time Tab Extension
  Time-Tab Manager/README.md
  Time-Tab Manager/clock.js
  Time-Tab Manager/icons/icon128.png
  Time-Tab Manager/icons/icon16.png
  Time-Tab Manager/icons/icon48.png
  Time-Tab Manager/image-fetcher.js
  Time-Tab Manager/index.html
  Time-Tab Manager/manifest.json
  Time-Tab Manager/style.css
Labels: good first issue, hacktoberfest-accepted, feature

#68 Added flight extension
  Flight_Extension/Airport.json
  Flight_Extension/README.md
  Flight_Extension/ZZ5H.gif
  Flight_Extension/index.html
  Flight_Extension/index.js
  Flight_Extension/manifest.json
  Flight_Extension/pngwing.com 2.png
  Flight_Extension/pngwing.com.png
  Flight_Extension/style.css
Labels: good first issue

#72 Website Blocker Extension
  Website_Blocker/README.md
  Website_Blocker/lock128.png
  Website_Blocker/lock48.png
  Website_Blocker/lock96.png
  Website_Blocker/manifest.json
  Website_Blocker/popup.html
  Website_Blocker/popup.js
  Website_Blocker/spectre.min.css
Labels: good first issue, hacktoberfest-accepted, feature

#73 Speech synthesis Extension added
  speech-synthesis-extension/Content.js
  speech-synthesis-extension/Popup.html
  speech-synthesis-extension/manifest.json
  speech-synthesis-extension/style.css
Labels: hacktoberfest-accepted, feature
